# ツリー表示
[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = '''
  let g:fern#default_hidden=1
'''
[[plugins]]
repo = 'yuki-yano/fern-preview.vim'

# ペア補完
[[plugins]]
repo = 'jiangmiao/auto-pairs'

# 多言語色変え
[[plugins]]
repo = 'sheerun/vim-polyglot'

# ステータスバーカスタマイズ
# [[plugins]]
# repo = 'vim-airline/vim-airline'
# [[plugins]]
# repo = 'vim-airline/vim-airline-themes'
# [[plugins]]
# repo = 'ryanoasis/vim-devicons'
# hook_add = '''
#   let g:airline_theme='dracula'
#   let g:airline#extensions#tabline#enabled=1
#   let g:airline_powerline_fonts=1
# '''

# Git用
[[plugins]]
repo = 'tpope/vim-fugitive'

# コメントアウト gcc gc
[[plugins]]
repo = 'tpope/vim-commentary'

# Language Server Protcol
# [[plugins]]
# repo = 'prabirshrestha/vim-lsp'
# [[plugins]]
# repo = 'prabirshrestha/async.vim'
# [[plugins]]
# repo = 'prabirshrestha/asyncomplete.vim'
# [[plugins]]
# repo = 'prabirshrestha/asyncomplete-lsp.vim'

# LSPの設定？
# [[plugins]]
# repo = 'mattn/vim-lsp-settings'

# c/c++補完
[[plugins]]
repo = 'justmao945/vim-clang'

# リンタ
# [[plugins]]
# repo = 'dense-analysis/ale'

# スニペット
[[plugins]]
repo = 'Shougo/neosnippet'
[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# Arduino syntax highlight
[[plugins]]
repo = 'sudar/vim-arduino-syntax'

# golang IDE
[[plugins]]
repo = 'fatih/vim-go'

# html auto close tag
[[plugins]]
repo = 'alvan/vim-closetag'

# ウィンドウのリサイズを簡単にする
[[plugins]]
repo = 'simeji/winresizer'

# ペアのタグを自動で変更 html
[[plugins]]
repo = 'AndrewRadev/tagalong.vim'

# カラースキーム用　ドラキュラ
# italicは文字が欠けるため無効化した
[[plugins]]
repo = 'dracula/vim'
hook_add = '''
  let g:dracula_italic = 0
'''

# Fern-drawerのアイコンをカスタマイズ
[[plugins]]
repo = 'lambdalisue/nerdfont.vim'
[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'
hook_add = '''
  let g:fern#renderer = 'nerdfont'
'''
[[plugins]]
repo = 'lambdalisue/glyph-palette.vim'
hook_add = '''
  augroup my-glyph-palette
    autocmd! *
    autocmd FileType fern call glyph_palette#apply()
    autocmd FileType nerdtree,startify call glyph_palette#apply()
  augroup END
'''
# Fernにgitの情報を表示
[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'

# csvファイルを色分け
[[plugins]]
repo = 'mechatroner/rainbow_csv'

# ヤンクハイライト
[[plugins]]
repo = 'machakann/vim-highlightedyank'

# emmet for vim
[[plugins]]
repo = 'mattn/emmet-vim'

# 対応タグのハイライト
[[plugins]]
repo = 'valloric/matchtagalways'

# インデント階層のガイド
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
  let g:indent_guides_enable_on_vim_startup = 1
'''

# css カラーコード　色付け
[[plugins]]
repo = 'gorodinskiy/vim-coloresque'

# 爆速カーソル移動
[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
  " <Leader>f{char} to move to {char}
  map  <Leader>f <Plug>(easymotion-bd-f)
  nmap <Leader>f <Plug>(easymotion-overwin-f)

  " s{char}{char} to move to {char}{char}
  nmap s <Plug>(easymotion-overwin-f2)

  " Move to line
  map <Leader>L <Plug>(easymotion-bd-jk)
  nmap <Leader>L <Plug>(easymotion-overwin-line)

  " Move to word
  map  <Leader>w <Plug>(easymotion-bd-w)
  nmap <Leader>w <Plug>(easymotion-overwin-w)
'''

# vimセッション保存
[[plugins]]
repo = 'tpope/vim-obsession'

# 文字補完
# [[plugins]]
# repo = 'Shougo/ddc.vim'
# [[plugins]]
# repo = 'vim-denops/denops.vim'
# [[plugins]]
# repo = 'Shougo/pum.vim'
# [[plugins]]
# repo = 'Shougo/ddc-around'
# [[plugins]]
# repo = 'LumaKernel/ddc-file'
# [[plugins]]
# repo = 'Shougo/ddc-matcher_head'
# [[plugins]]
# repo = 'Shougo/ddc-sorter_rank'
# [[plugins]]
# repo = 'shun/ddc-vim-lsp'
# [[plugins]]
# repo = 'Shougo/ddc-ui-native'
# hook_add = '''
#   call ddc#custom#patch_global('ui', 'native')
# '''
# [[plugins]]
# repo = 'Shougo/ddc-converter_remove_overlap'
# hook_add = '''
#   call ddc#custom#patch_global('sources', [
#    \ 'around',
#    \ 'vim-lsp',
#    \ 'file'
#    \ ])
#   call ddc#custom#patch_global('sourceOptions', {
#    \ '_': {
#    \   'matchers': ['matcher_head'],
#    \   'sorters': ['sorter_rank'],
#    \   'converters': ['converter_remove_overlap'],
#    \ },
#    \ 'around': {'mark': 'Around'},
#    \ 'vim-lsp': {
#    \   'mark': 'LSP',
#    \   'matchers': ['matcher_head'],
#    \   'forceCompletionPattern': '\.|:|->|"\w+/*'
#    \ },
#    \ 'file': {
#    \   'mark': 'file',
#    \   'isVolatile': v:true,
#    \   'forceCompletionPattern': '\S/\S*'
#    \ }})
#   call ddc#enable()
#   let g:denops_disable_version_check = 1
#   " <TAB>: completion.
#   inoremap <silent><expr> <TAB>
#   \ ddc#map#pum_visible() ? '<C-n>' :
#   \ (col('.') <= 1 <Bar><Bar> getline('.')[col('.') - 2] =~# '\s') ?
#   \ '<TAB>' : ddc#map#manual_complete()
#   " <S-TAB>: completion back.
#   inoremap <expr><S-TAB>  ddc#map#pum_visible() ? '<C-p>' : '<C-h>'
# '''

# vim-lspのせいで動作が遅くなるため、抜いたdcc.vim
[[plugins]]
repo = 'Shougo/ddc.vim'
[[plugins]]
repo = 'vim-denops/denops.vim'
[[plugins]]
repo = 'Shougo/pum.vim'
[[plugins]]
repo = 'Shougo/ddc-around'
[[plugins]]
repo = 'LumaKernel/ddc-file'
[[plugins]]
repo = 'Shougo/ddc-matcher_head'
[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
[[plugins]]
repo = 'Shougo/ddc-ui-native'
hook_add = '''
  call ddc#custom#patch_global('ui', 'native')
'''
[[plugins]]
repo = 'Shougo/ddc-converter_remove_overlap'
hook_add = '''
  call ddc#custom#patch_global('sources', [
   \ 'around',
   \ 'file'
   \ ])
  call ddc#custom#patch_global('sourceOptions', {
   \ '_': {
   \   'matchers': ['matcher_head'],
   \   'sorters': ['sorter_rank'],
   \   'converters': ['converter_remove_overlap'],
   \ },
   \ 'file': {
   \   'mark': 'file',
   \   'isVolatile': v:true,
   \   'forceCompletionPattern': '\S/\S*'
   \ }})
  call ddc#enable()
  let g:denops_disable_version_check = 1
  " <TAB>: completion.
  inoremap <silent><expr> <TAB>
  \ ddc#map#pum_visible() ? '<C-n>' :
  \ (col('.') <= 1 <Bar><Bar> getline('.')[col('.') - 2] =~# '\s') ?
  \ '<TAB>' : ddc#map#manual_complete()
  " <S-TAB>: completion back.
  inoremap <expr><S-TAB>  ddc#map#pum_visible() ? '<C-p>' : '<C-h>'
'''

# ファイル検索
[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

# 括弧を一発変換
[[plugins]]
repo = 'tpope/vim-surround'
