# ツリー表示
[[plugins]]
repo = 'lambdalisue/fern.vim'
[[plugins]]
repo = 'yuki-yano/fern-preview.vim'

# ペア補完
[[plugins]]
repo = 'jiangmiao/auto-pairs'

# 多言語色変え
[[plugins]]
repo = 'sheerun/vim-polyglot'

# ステータスバーカスタマイズ
[[plugins]]
repo = 'vim-airline/vim-airline'
[[plugins]]
repo = 'vim-airline/vim-airline-themes'
[[plugins]]
repo = 'ryanoasis/vim-devicons'
hook_add = '''
  let g:airline_theme='dracula'
  let g:airline#extensions#tabline#enabled=1
  let g:airline_powerline_fonts=1
'''

# Git用
[[plugins]]
repo = 'tpope/vim-fugitive'

# コメントアウト gcc gc
[[plugins]]
repo = 'tpope/vim-commentary'

# タブ補完
[[plugins]]
repo = 'ervandew/supertab'

# Language Server Protcol
[[plugins]]
repo = 'prabirshrestha/vim-lsp'
[[plugins]]
repo = 'prabirshrestha/async.vim'
[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

# LSPの設定？
[[plugins]]
repo = 'mattn/vim-lsp-settings'

# c/c++補完
[[plugins]]
repo = 'justmao945/vim-clang'

# リンタ
[[plugins]]
repo = 'dense-analysis/ale'

# スニペット
[[plugins]]
repo = 'Shougo/neosnippet'
[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# Arduino syntax highlight
[[plugins]]
repo = 'sudar/vim-arduino-syntax'

# golang IDE
[[plugins]]
repo = 'fatih/vim-go'

# html auto close tag
[[plugins]]
repo = 'alvan/vim-closetag'

# ウィンドウのリサイズを簡単にする
[[plugins]]
repo = 'simeji/winresizer'

# ペアのタグを自動で変更 html
[[plugins]]
repo = 'AndrewRadev/tagalong.vim'

# カラースキーム用　ドラキュラ
[[plugins]]
repo = 'dracula/vim'

# Fern-drawerのアイコンをカスタマイズ
[[plugins]]
repo = 'lambdalisue/nerdfont.vim'
[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'
hook_add = '''
  let g:fern#renderer = 'nerdfont'
'''
[[plugins]]
repo = 'lambdalisue/glyph-palette.vim'
hook_add = '''
  augroup my-glyph-palette
    autocmd! *
    autocmd FileType fern call glyph_palette#apply()
    autocmd FileType nerdtree,startify call glyph_palette#apply()
  augroup END
'''
# Fernにgitの情報を表示
[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'

# csvファイルを色分け
[[plugins]]
repo = 'mechatroner/rainbow_csv'

# ヤンクハイライト
[[plugins]]
repo = 'machakann/vim-highlightedyank'

# emmet for vim
[[plugins]]
repo = 'mattn/emmet-vim'

# 対応タグのハイライト
[[plugins]]
repo = 'valloric/matchtagalways'

# インデント階層のガイド
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
  let g:indent_guides_enable_on_vim_startup = 1
'''

# css カラーコード　色付け
[[plugins]]
repo = 'gorodinskiy/vim-coloresque'

# 爆速カーソル移動
[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
  " <Leader>f{char} to move to {char}
  map  <Leader>f <Plug>(easymotion-bd-f)
  nmap <Leader>f <Plug>(easymotion-overwin-f)

  " s{char}{char} to move to {char}{char}
  nmap s <Plug>(easymotion-overwin-f2)

  " Move to line
  map <Leader>L <Plug>(easymotion-bd-jk)
  nmap <Leader>L <Plug>(easymotion-overwin-line)

  " Move to word
  map  <Leader>w <Plug>(easymotion-bd-w)
  nmap <Leader>w <Plug>(easymotion-overwin-w)
'''
